services:
  mongodb:
    image: mongo:7.0
    container_name: cqrs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cqrs_db
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - cqrs-network

networks:
  cqrs-network:
    driver: bridge

volumes:
  mongodb_data:
  mongodb_config: