services: 
  api-express-template-db:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=cqrs-example-user
      - POSTGRESQL_PASSWORD=cqrs-example-pass
      - POSTGRESQL_DATABASE=cqrs-example-db